In [1]:
from QuantNodes.factor_table.FactorPool import FactorPool
from QuantNodes.factor_table.Factors import FactorUnit
import numpy as np
import pandas as pd

In [2]:
from ClickSQL import BaseSingleFactorTableNode

In [3]:
f_ = FactorPool()
np.random.seed(1)
df = pd.DataFrame(np.random.random(size=(1000, 4)), columns=['cik_dts', 'cik_iid', 'v1', 'v2'])
f1 = FactorUnit('test', df, 'cik_dts', 'cik_iid', factor_names=['v1', 'v2'])

df = pd.DataFrame(np.random.random(size=(1000, 3)), columns=['cik_dts', 'cik_iid', 'v3'])
f2 = FactorUnit('test2', df, 'cik_dts', 'cik_iid', factor_names=['v3'])
# query = node.query
# f3 = FactorUnit('test.test2', query, 'cik_dts', 'cik_iid', factor_names=['v3'])

f_.add_factor(f1)
f_.add_factor(f2)
# f_.append(f3)

In [4]:
f_.show_factors(to_df=True)

,db_table,dts,iid,origin_factor_names,alias,sql,via,info
0,cik_dts cik_iid v1 v2 0 ...,cik_dts,cik_iid,"v1,v2","None,None",,DF,
1,cik_dts cik_iid v3 0 0.35884...,cik_dts,cik_iid,v3,None,,DF,

In [5]:
node = BaseSingleFactorTableNode('clickhouse://default:***REMOVED***@***REMOVED***:8123/system')
node('show tables from EDGAR_LOG')

connection test:  Ok.

                  name
0             base_url
1                 days
2        downloaded_dt
3            edgar_log
4        edgar_log_raw
5        hours_statics
6       log_file_tasks
7              monitor
8     parsed_edgar_log
9  rest_log_file_tasks

In [6]:
node('select * from EDGAR_LOG.parsed_edgar_log limit 10')

,ip,date,time,zone,cik,accession,extention,code,size,idx,norefer,noagent,find,crawler,browser
0,104.155.127.aha,2017-04-30,00:00:00,0.0,1083446,0001676960-16-000002,.txt,200,6064,0,0,0,10,0,   
1,104.155.169.jbh,2017-04-30,00:00:00,0.0,1218304,0001140361-03-004442,.txt,200,2998,0,0,0,10,0,   
2,104.155.169.jbh,2017-04-30,00:00:00,0.0,1218304,0001140361-03-004429,.txt,200,2916,0,0,0,10,0,   
3,104.155.169.jbh,2017-04-30,00:00:00,0.0,1218307,0001179110-03-010077,.txt,200,2691,0,0,0,10,0,   
4,104.198.37.bdc,2017-04-30,00:00:00,0.0,1688418,0001209191-17-028829,-index.htm,200,2829,1,0,0,9,0,   
5,104.198.37.bdc,2017-04-30,00:00:00,0.0,1688418,0001209191-17-028829,-index.htm,301,684,1,0,0,10,0,   
6,106.120.173.jie,2017-04-30,00:00:00,0.0,929058,0001341004-13-001177,form6k.htm,304,243,0,0,0,10,0,   
7,107.23.85.jfd,2017-04-30,00:00:00,0.0,1097202,0001056404-00-000199,-index.html,200,2710,1,0,0,10,0,   
8,107.23.85.jfd,2017-04-30,00:00:00,0.0,1097202,0000950136-00-000949,-index.htm,200,2672,1,0,0,10,0,   
9,107.23.85.jfd,2017-04-30,00:00:00,0.0,1375790,0001162318-06-001268,-index.htm,200,2697,1,0,0,10,0,   

In [7]:
node('select * from EDGAR_LOG.parsed_edgar_log limit 10')

,ip,date,time,zone,cik,accession,extention,code,size,idx,norefer,noagent,find,crawler,browser
0,104.155.127.aha,2017-04-30,00:00:00,0.0,1083446,0001676960-16-000002,.txt,200,6064,0,0,0,10,0,   
1,104.155.169.jbh,2017-04-30,00:00:00,0.0,1218304,0001140361-03-004442,.txt,200,2998,0,0,0,10,0,   
2,104.155.169.jbh,2017-04-30,00:00:00,0.0,1218304,0001140361-03-004429,.txt,200,2916,0,0,0,10,0,   
3,104.155.169.jbh,2017-04-30,00:00:00,0.0,1218307,0001179110-03-010077,.txt,200,2691,0,0,0,10,0,   
4,104.198.37.bdc,2017-04-30,00:00:00,0.0,1688418,0001209191-17-028829,-index.htm,200,2829,1,0,0,9,0,   
5,104.198.37.bdc,2017-04-30,00:00:00,0.0,1688418,0001209191-17-028829,-index.htm,301,684,1,0,0,10,0,   
6,106.120.173.jie,2017-04-30,00:00:00,0.0,929058,0001341004-13-001177,form6k.htm,304,243,0,0,0,10,0,   
7,107.23.85.jfd,2017-04-30,00:00:00,0.0,1097202,0001056404-00-000199,-index.html,200,2710,1,0,0,10,0,   
8,107.23.85.jfd,2017-04-30,00:00:00,0.0,1097202,0000950136-00-000949,-index.htm,200,2672,1,0,0,10,0,   
9,107.23.85.jfd,2017-04-30,00:00:00,0.0,1375790,0001162318-06-001268,-index.htm,200,2697,1,0,0,10,0,   

In [8]:
f2 = FactorPool()

In [9]:
f2.add_factor('EDGAR_LOG.parsed_edgar_log',node,'date','ip','code')
f2.add_factor('EDGAR_LOG.parsed_edgar_log',node,'date','ip','size,crawler')

C:\Users\user\Documents\GitHub\QuantNodes\QuantNodes\factor_table\Factors.py:139: UserWarning: query dont have src property! will set as random src! please check src!
  warnings.warn('query dont have src property! will set as random src! please check src!')

In [10]:
f2.add_factor('select * from EDGAR_LOG.parsed_edgar_log',node,'date','ip','idx,cik,noagent')

In [11]:
f2[0].factor_info()

FactorInfo(db_table='EDGAR_LOG.parsed_edgar_log', dts='date', iid='ip', origin_factor_names='code', alias='None', sql='', via='db_table_ClickHouse', info='0.177031054599608')

In [12]:
f2[1].factor_info()

FactorInfo(db_table='EDGAR_LOG.parsed_edgar_log', dts='date', iid='ip', origin_factor_names='size,crawler', alias='None,None', sql='', via='db_table_ClickHouse', info='0.40175643020703267')

In [13]:
f2.show_factors(reduced=True)

                                   db_table   dts iid origin_factor_names  \
0                EDGAR_LOG.parsed_edgar_log  date  ip                code
1                EDGAR_LOG.parsed_edgar_log  date  ip        size,crawler
2  select * from EDGAR_LOG.parsed_edgar_log  date  ip     idx,cik,noagent

            alias                                       sql  \
0            None
1       None,None
2  None,None,None  select * from EDGAR_LOG.parsed_edgar_log

                   via                   info
0  db_table_ClickHouse      0.177031054599608
1  db_table_ClickHouse    0.40175643020703267
2       SQL_ClickHouse  0.0029414434162440273

AttributeError: 'Series' object has no attribute 'split'